Update vault-to-yaml-appVersion.yml

diff --git a/.github/workflows/vault-to-yaml-appVersion.yml b/.github/workflows/vault-to-yaml-appVersion.yml
--- a/.github/workflows/vault-to-yaml-appVersion.yml
+++ b/.github/workflows/vault-to-yaml-appVersion.yml
@@ -52,12 +52,16 @@ jobs:
 
 
           ORG=$(get_secret SINGLESTORE_ORG_ID)
+          if [[ -z "$ORG" || "$ORG" == "null" ]]; then
+            echo " Error: Secreto SINGLESTORE_ORG_ID vacío o no encontrado."
+            exit 1
+          fi
           GROUP=$(get_secret SINGLESTORE_WORKSPACE_GROUP_ID)
           KEY=$(get_secret SINGLESTORE_API_KEY)
 
           # Validaciones
           if [[ -z "$ORG" || -z "$GROUP" || -z "$KEY" ]]; then
-            echo "❌ Error: Uno o más secretos están vacíos o no existen."
+            echo " Error: Uno o más secretos están vacíos o no existen."
             exit 1
           fi
 
